# Generated by Django 3.2.19 on 2023-05-11 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('update_needed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('is_upper_60_percent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PostToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.post')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.token')),
            ],
        ),
        migrations.CreateModel(
            name='PostSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.post')),
                ('related_tokens', models.ManyToManyField(blank=True, to='board.Token')),
                ('similar_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_post', to='board.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='related_posts',
            field=models.ManyToManyField(blank=True, related_name='_board_post_related_posts_+', through='board.PostSimilarity', to='board.Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='tokens',
            field=models.ManyToManyField(through='board.PostToken', to='board.Token'),
        ),
    ]
