name: ci

on:
    push:
        tags:
            - "v*"

jobs:
    image-push:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set env
              run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
            - name: Make envfile
              uses: SpicyPizza/create-envfile@v1.3
              with:
                  directory: ./
                  envkey_DB_NAME: ${{ secrets.DB_NAME }}
                  envkey_DB_USER: ${{ secrets.DB_USER }}
                  envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to Docker Registry
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USER }}
                  password: ${{ secrets.DOCKERHUB_PWD }}
            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: |
                      gczzga/kyj-board:latest
                      gczzga/kyj-board:${{ env.RELEASE_VERSION }}
